version: "2017-09-20"
pipeline:
- id: build
  overlay: guild-python/latest
  type: script
  env:
    PYENV_VERSION: "3.7"
  commands:
  - desc: Test package
    cmd: |
      pip3 install -U flake8
      flake8 .
      tox

  - desc: SonarQube analysis
    cmd: |
      poetry run pylint -j 0 zmon_agent > pylint-report.txt || true # never fail here
      sonar-client

  - desc: "Push Docker Image"
    cmd: |
      IMAGE=pierone.stups.zalan.do/metrics/zmon-agent-core:${CDP_BUILD_VERSION}

      if ! docker pull "$IMAGE"; then
          echo "$IMAGE does not exist, building and pushing to pierone ..."
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
      else
          echo "Image already exists. Skipping building and pushing: $IMAGE"
      fi

- id: staging
  desc: "Deploy staging environment"
  type: process
  target: stups-test
  process: microservice_standard_deployment
  config:
    apply_permanent_resources:
      env:
      - name: IMAGE
        value: "pierone.stups.zalan.do/metrics/zmon-agent-core:#{CDP_BUILD_VERSION}"
      - name: OAUTH2_ACCESS_TOKEN_URL
        value: "https://sandbox.identity.zalando.com/oauth2/token?business_partner_id=810d1d00-4312-43e5-bd31-d8373fdd24c7"



notifications:
- channel: google_chat
  rooms:
  - AAAAe-hg3KE
  config:
    emoji_pack: emotional
