version: "2017-09-20"
dependencies:
  - id: agent
    type: docker
    ref: registry.opensource.zalan.do/zmon/zmon-agent-core

  - id: agent_unstable
    type: docker
    ref: registry.opensource.zalan.do/zmon/zmon-agent-core-unstable

pipeline:
  - id: build
    type: script
    commands:
      - desc: "Install dependencies"
        cmd: |
          apt-get install -q -y --no-install-recommends git
          curl -fLOsS https://delivery.cloud.zalando.com/utils/ensure-docker && sh ensure-docker && rm ensure-docker

      - desc: "Build and push zmon-agent-core"
        cmd: |
          IS_PR_BUILD=${CDP_PULL_REQUEST_NUMBER+"true"}
          if [ "${IS_PR_BUILD}" != "true" ]
          then
            INTERNAL_VERSION=$(git describe --tags --always --dirty)
            VERSION=${DEP_AGENT_VERSION}-${INTERNAL_VERSION}
            IMAGE=pierone.stups.zalan.do/zmon/zmon-agent-core:${VERSION}

            if ! docker pull "$IMAGE"; then
                echo "zmon-agent-core:$VERSION does not exist, building and pushing to pierone ..."
                docker build -f zmon-agent-core.docker --build-arg BASE_IMAGE=zmon-agent-core --build-arg BASE_IMAGE_VERSION="${DEP_AGENT_VERSION}" -t "$IMAGE" .
                docker push "$IMAGE"
            else
                echo "Image already exists. Skipping building and pushing: zmon-agent-core:$VERSION"
            fi
          else
            echo "PR build, skipping building step!"
          fi

      - desc: "Build and push zmon-agent-core-unstable"
        cmd: |
          INTERNAL_VERSION=$(git describe --tags --always --dirty)
          VERSION=${DEP_AGENT_UNSTABLE_VERSION}-${INTERNAL_VERSION}
          IMAGE=pierone.stups.zalan.do/zmon/zmon-agent-core-unstable:${VERSION}

          if ! docker pull "$IMAGE"; then
              echo "zmon-agent-core-unstable:$VERSION does not exist, building and pushing to pierone ..."
              docker build -f zmon-agent-core.docker --build-arg BASE_IMAGE=zmon-agent-core-unstable --build-arg  BASE_IMAGE_VERSION=${DEP_AGENT_UNSTABLE_VERSION} -t "$IMAGE" .
              docker push "$IMAGE"
          else
              echo "Image already exists. Skipping building and pushing: zmon-agent-core-unstable:$VERSION"
          fi
