version: "2017-09-20"
pipeline:
- id: build
  overlay: guild-python/latest
  type: script
  env:
    PYENV_VERSION: "3.7"
  commands:
  - desc: Test package
    cmd: |
      pip3 install -U flake8
      flake8 .
      tox

  - desc: SonarQube analysis
    cmd: |
      poetry run pylint -j 0 zmon_agent > pylint-report.txt || true # never fail here
      sonar-client

  - desc: "Push Docker Image"
    cmd: |
      IMAGE=pierone.stups.zalan.do/zmon/zmon-agent-core:${CDP_BUILD_VERSION}

      if ! docker pull "$IMAGE"; then
          echo "$IMAGE does not exist, building and pushing to pierone ..."
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
      else
          echo "Image already exists. Skipping building and pushing: $IMAGE"
      fi

notifications:
- channel: google_chat
  rooms:
  - AAAAe-hg3KE
  config:
    emoji_pack: emotional
